// Auto-generated by scripts/gen-supabase-types.mjs
// Do not edit this file manually.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.1"
  }
  public: {
    Tables: {
      calibration_audit: {
        Row: {
          approved: boolean | null
          approved_by: string | null
          audit_id: string
          calibration_type: string
          created_at: string
          metrics: Json
          notes: string | null
          parameters: Json
          scoring_version: number
        }
        Insert: {
          approved?: boolean | null
          approved_by?: string | null
          audit_id?: string
          calibration_type: string
          created_at?: string
          metrics?: Json
          notes?: string | null
          parameters?: Json
          scoring_version: number
        }
        Update: {
          approved?: boolean | null
          approved_by?: string | null
          audit_id?: string
          calibration_type?: string
          created_at?: string
          metrics?: Json
          notes?: string | null
          parameters?: Json
          scoring_version?: number
        }
        Relationships: []
      }
      claims: {
        Row: {
          claim_text: string
          confidence_score: number | null
          conflict_basis: string | null
          created_at: string
          document_id: string
          gap_reason: string | null
          id: string
          risk_level: string | null
          segment_id: string
          sire_exclusions: Json | null
          sire_information: Json | null
          sire_retrieval: Json | null
          sire_scope: Json | null
          veracity_label: string | null
        }
        Insert: {
          claim_text: string
          confidence_score?: number | null
          conflict_basis?: string | null
          created_at?: string
          document_id: string
          gap_reason?: string | null
          id?: string
          risk_level?: string | null
          segment_id: string
          sire_exclusions?: Json | null
          sire_information?: Json | null
          sire_retrieval?: Json | null
          sire_scope?: Json | null
          veracity_label?: string | null
        }
        Update: {
          claim_text?: string
          confidence_score?: number | null
          conflict_basis?: string | null
          created_at?: string
          document_id?: string
          gap_reason?: string | null
          id?: string
          risk_level?: string | null
          segment_id?: string
          sire_exclusions?: Json | null
          sire_information?: Json | null
          sire_retrieval?: Json | null
          sire_scope?: Json | null
          veracity_label?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "claims_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "documents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "claims_segment_id_fkey"
            columns: ["segment_id"]
            isOneToOne: false
            referencedRelation: "segments"
            referencedColumns: ["id"]
          },
        ]
      }
      documents: {
        Row: {
          author: string | null
          corpus_front_matter: Json | null
          created_at: string
          enriched_entities: string[] | null
          enriched_event_type: string | null
          enriched_geo: string | null
          event_id: string | null
          event_key: string | null
          factuality_score: number | null
          feed_id: string
          fetch_status: string
          grounding_score: number | null
          id: string
          ideology_scores: Json | null
          integrity_score: number | null
          normalized_content: string | null
          one_sidedness: number | null
          pipeline_status: string
          published_at: string | null
          raw_content: string | null
          sentiment_compound: number | null
          sentiment_neg: number | null
          sentiment_neu: number | null
          sentiment_pos: number | null
          sourcing_quality: number | null
          story_id: string | null
          strip: Json | null
          synthesis_sources: Json | null
          synthesis_text: string | null
          title: string | null
          updated_at: string
          url: string
          word_count: number | null
        }
        Insert: {
          author?: string | null
          corpus_front_matter?: Json | null
          created_at?: string
          enriched_entities?: string[] | null
          enriched_event_type?: string | null
          enriched_geo?: string | null
          event_id?: string | null
          event_key?: string | null
          factuality_score?: number | null
          feed_id: string
          fetch_status?: string
          grounding_score?: number | null
          id?: string
          ideology_scores?: Json | null
          integrity_score?: number | null
          normalized_content?: string | null
          one_sidedness?: number | null
          pipeline_status?: string
          published_at?: string | null
          raw_content?: string | null
          sentiment_compound?: number | null
          sentiment_neg?: number | null
          sentiment_neu?: number | null
          sentiment_pos?: number | null
          sourcing_quality?: number | null
          story_id?: string | null
          strip?: Json | null
          synthesis_sources?: Json | null
          synthesis_text?: string | null
          title?: string | null
          updated_at?: string
          url: string
          word_count?: number | null
        }
        Update: {
          author?: string | null
          corpus_front_matter?: Json | null
          created_at?: string
          enriched_entities?: string[] | null
          enriched_event_type?: string | null
          enriched_geo?: string | null
          event_id?: string | null
          event_key?: string | null
          factuality_score?: number | null
          feed_id?: string
          fetch_status?: string
          grounding_score?: number | null
          id?: string
          ideology_scores?: Json | null
          integrity_score?: number | null
          normalized_content?: string | null
          one_sidedness?: number | null
          pipeline_status?: string
          published_at?: string | null
          raw_content?: string | null
          sentiment_compound?: number | null
          sentiment_neg?: number | null
          sentiment_neu?: number | null
          sentiment_pos?: number | null
          sourcing_quality?: number | null
          story_id?: string | null
          strip?: Json | null
          synthesis_sources?: Json | null
          synthesis_text?: string | null
          title?: string | null
          updated_at?: string
          url?: string
          word_count?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "documents_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "documents_feed_id_fkey"
            columns: ["feed_id"]
            isOneToOne: false
            referencedRelation: "feeds"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "documents_story_id_fkey"
            columns: ["story_id"]
            isOneToOne: false
            referencedRelation: "stories"
            referencedColumns: ["id"]
          },
        ]
      }
      event_story_links: {
        Row: {
          created_at: string
          event_id: string
          id: string
          link_score: number | null
          story_id: string
        }
        Insert: {
          created_at?: string
          event_id: string
          id?: string
          link_score?: number | null
          story_id: string
        }
        Update: {
          created_at?: string
          event_id?: string
          id?: string
          link_score?: number | null
          story_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "event_story_links_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "event_story_links_story_id_fkey"
            columns: ["story_id"]
            isOneToOne: false
            referencedRelation: "stories"
            referencedColumns: ["id"]
          },
        ]
      }
      events: {
        Row: {
          algo_version: number
          claim_centroid: string | null
          cluster_entities: string[]
          created_at: string
          doc_centroid: string | null
          document_count: number
          entities: string[]
          event_key: string | null
          event_type: string
          geo_primary: string | null
          id: string
          summary: string | null
          time_bucket: string | null
          title: string | null
          topics: string[]
          updated_at: string
        }
        Insert: {
          algo_version?: number
          claim_centroid?: string | null
          cluster_entities?: string[]
          created_at?: string
          doc_centroid?: string | null
          document_count?: number
          entities?: string[]
          event_key?: string | null
          event_type?: string
          geo_primary?: string | null
          id?: string
          summary?: string | null
          time_bucket?: string | null
          title?: string | null
          topics?: string[]
          updated_at?: string
        }
        Update: {
          algo_version?: number
          claim_centroid?: string | null
          cluster_entities?: string[]
          created_at?: string
          doc_centroid?: string | null
          document_count?: number
          entities?: string[]
          event_key?: string | null
          event_type?: string
          geo_primary?: string | null
          id?: string
          summary?: string | null
          time_bucket?: string | null
          title?: string | null
          topics?: string[]
          updated_at?: string
        }
        Relationships: []
      }
      evidence: {
        Row: {
          claim_id: string
          created_at: string
          evidence_text: string
          id: string
          is_independent: boolean | null
          nli_confidence: number | null
          nli_label: string | null
          similarity_score: number | null
          source_publisher: string | null
          source_segment_id: string | null
          source_tier: string
          source_url: string | null
        }
        Insert: {
          claim_id: string
          created_at?: string
          evidence_text: string
          id?: string
          is_independent?: boolean | null
          nli_confidence?: number | null
          nli_label?: string | null
          similarity_score?: number | null
          source_publisher?: string | null
          source_segment_id?: string | null
          source_tier: string
          source_url?: string | null
        }
        Update: {
          claim_id?: string
          created_at?: string
          evidence_text?: string
          id?: string
          is_independent?: boolean | null
          nli_confidence?: number | null
          nli_label?: string | null
          similarity_score?: number | null
          source_publisher?: string | null
          source_segment_id?: string | null
          source_tier?: string
          source_url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "evidence_claim_id_fkey"
            columns: ["claim_id"]
            isOneToOne: false
            referencedRelation: "claims"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "evidence_source_segment_id_fkey"
            columns: ["source_segment_id"]
            isOneToOne: false
            referencedRelation: "segments"
            referencedColumns: ["id"]
          },
        ]
      }
      feeds: {
        Row: {
          created_at: string
          description: string | null
          id: string
          is_active: boolean
          last_polled_at: string | null
          polling_interval_minutes: number
          publisher_name: string
          source_category: string
          updated_at: string
          url: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          is_active?: boolean
          last_polled_at?: string | null
          polling_interval_minutes?: number
          publisher_name: string
          source_category?: string
          updated_at?: string
          url: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          is_active?: boolean
          last_polled_at?: string | null
          polling_interval_minutes?: number
          publisher_name?: string
          source_category?: string
          updated_at?: string
          url?: string
        }
        Relationships: []
      }
      ideology_scores: {
        Row: {
          created_at: string
          entity_id: string
          entity_type: string
          mean_confidence: number
          metadata: Json | null
          method: string
          model_id: string
          n_propositions: number
          n_stances: number
          score_id: string
          scoring_version: number
          se: number | null
          theta_economic: number | null
          theta_normalized: number | null
          theta_raw: number | null
          theta_social: number | null
        }
        Insert: {
          created_at?: string
          entity_id: string
          entity_type: string
          mean_confidence?: number
          metadata?: Json | null
          method: string
          model_id?: string
          n_propositions?: number
          n_stances?: number
          score_id?: string
          scoring_version?: number
          se?: number | null
          theta_economic?: number | null
          theta_normalized?: number | null
          theta_raw?: number | null
          theta_social?: number | null
        }
        Update: {
          created_at?: string
          entity_id?: string
          entity_type?: string
          mean_confidence?: number
          metadata?: Json | null
          method?: string
          model_id?: string
          n_propositions?: number
          n_stances?: number
          score_id?: string
          scoring_version?: number
          se?: number | null
          theta_economic?: number | null
          theta_normalized?: number | null
          theta_raw?: number | null
          theta_social?: number | null
        }
        Relationships: []
      }
      inoreader_tokens: {
        Row: {
          access_token: string
          created_at: string
          expires_at: string
          id: string
          refresh_token: string
          updated_at: string
        }
        Insert: {
          access_token: string
          created_at?: string
          expires_at: string
          id?: string
          refresh_token: string
          updated_at?: string
        }
        Update: {
          access_token?: string
          created_at?: string
          expires_at?: string
          id?: string
          refresh_token?: string
          updated_at?: string
        }
        Relationships: []
      }
      pipeline_control: {
        Row: {
          failure_streak: number
          pause_reason: string | null
          paused: boolean
          paused_until: string | null
          stage: string
          updated_at: string
        }
        Insert: {
          failure_streak?: number
          pause_reason?: string | null
          paused?: boolean
          paused_until?: string | null
          stage: string
          updated_at?: string
        }
        Update: {
          failure_streak?: number
          pause_reason?: string | null
          paused?: boolean
          paused_until?: string | null
          stage?: string
          updated_at?: string
        }
        Relationships: []
      }
      pipeline_dlq: {
        Row: {
          attempt: number
          doc_id: string
          error_message: string | null
          failed_at: string
          id: string
          payload: Json | null
          stage: string
        }
        Insert: {
          attempt?: number
          doc_id: string
          error_message?: string | null
          failed_at?: string
          id?: string
          payload?: Json | null
          stage: string
        }
        Update: {
          attempt?: number
          doc_id?: string
          error_message?: string | null
          failed_at?: string
          id?: string
          payload?: Json | null
          stage?: string
        }
        Relationships: []
      }
      pipeline_enqueue_guard: {
        Row: {
          created_at: string
          doc_id: string
          stage: string
          status_token: string
        }
        Insert: {
          created_at?: string
          doc_id: string
          stage: string
          status_token: string
        }
        Update: {
          created_at?: string
          doc_id?: string
          stage?: string
          status_token?: string
        }
        Relationships: []
      }
      pipeline_stage_metrics: {
        Row: {
          attempt: number
          created_at: string
          document_id: string | null
          duration_ms: number
          error_message: string | null
          id: number
          stage: string
          status: string
        }
        Insert: {
          attempt: number
          created_at?: string
          document_id?: string | null
          duration_ms: number
          error_message?: string | null
          id?: number
          stage: string
          status: string
        }
        Update: {
          attempt?: number
          created_at?: string
          document_id?: string | null
          duration_ms?: number
          error_message?: string | null
          id?: number
          stage?: string
          status?: string
        }
        Relationships: []
      }
      proposition_bank: {
        Row: {
          axis: string
          created_at: string
          deprecated_at: string | null
          difficulty_b: number
          dimension: string | null
          discrimination_a: number
          domain: string
          embedding: string | null
          keywords: string[]
          liberal_is_pro: boolean
          notes: string | null
          proposition_id: string
          status: string
          text: string
          version: number
        }
        Insert: {
          axis: string
          created_at?: string
          deprecated_at?: string | null
          difficulty_b?: number
          dimension?: string | null
          discrimination_a?: number
          domain: string
          embedding?: string | null
          keywords?: string[]
          liberal_is_pro: boolean
          notes?: string | null
          proposition_id?: string
          status?: string
          text: string
          version?: number
        }
        Update: {
          axis?: string
          created_at?: string
          deprecated_at?: string | null
          difficulty_b?: number
          dimension?: string | null
          discrimination_a?: number
          domain?: string
          embedding?: string | null
          keywords?: string[]
          liberal_is_pro?: boolean
          notes?: string | null
          proposition_id?: string
          status?: string
          text?: string
          version?: number
        }
        Relationships: []
      }
      publisher_baselines: {
        Row: {
          avg_contradiction_rate: number | null
          avg_factuality_score: number | null
          avg_grounding_score: number | null
          avg_ideology_economic: number | null
          avg_ideology_social: number | null
          avg_integrity_score: number | null
          avg_one_sidedness: number | null
          avg_sourcing_quality: number | null
          computed_at: string
          document_count: number | null
          id: string
          period: string
          publisher_name: string
          segment_label_distribution: Json | null
        }
        Insert: {
          avg_contradiction_rate?: number | null
          avg_factuality_score?: number | null
          avg_grounding_score?: number | null
          avg_ideology_economic?: number | null
          avg_ideology_social?: number | null
          avg_integrity_score?: number | null
          avg_one_sidedness?: number | null
          avg_sourcing_quality?: number | null
          computed_at?: string
          document_count?: number | null
          id?: string
          period: string
          publisher_name: string
          segment_label_distribution?: Json | null
        }
        Update: {
          avg_contradiction_rate?: number | null
          avg_factuality_score?: number | null
          avg_grounding_score?: number | null
          avg_ideology_economic?: number | null
          avg_ideology_social?: number | null
          avg_integrity_score?: number | null
          avg_one_sidedness?: number | null
          avg_sourcing_quality?: number | null
          computed_at?: string
          document_count?: number | null
          id?: string
          period?: string
          publisher_name?: string
          segment_label_distribution?: Json | null
        }
        Relationships: []
      }
      segments: {
        Row: {
          classification: string | null
          created_at: string
          document_id: string
          embedding: string | null
          id: string
          label: string | null
          position_index: number
          rhetorical_flags: Json | null
          sentiment_compound: number | null
          sentiment_neg: number | null
          sentiment_neu: number | null
          sentiment_pos: number | null
          text_content: string
          token_count: number | null
        }
        Insert: {
          classification?: string | null
          created_at?: string
          document_id: string
          embedding?: string | null
          id?: string
          label?: string | null
          position_index: number
          rhetorical_flags?: Json | null
          sentiment_compound?: number | null
          sentiment_neg?: number | null
          sentiment_neu?: number | null
          sentiment_pos?: number | null
          text_content: string
          token_count?: number | null
        }
        Update: {
          classification?: string | null
          created_at?: string
          document_id?: string
          embedding?: string | null
          id?: string
          label?: string | null
          position_index?: number
          rhetorical_flags?: Json | null
          sentiment_compound?: number | null
          sentiment_neg?: number | null
          sentiment_neu?: number | null
          sentiment_pos?: number | null
          text_content?: string
          token_count?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "segments_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "documents"
            referencedColumns: ["id"]
          },
        ]
      }
      stance_extractions: {
        Row: {
          confidence: number
          created_at: string
          extraction_id: string
          model_id: string
          model_version: string
          proposition_id: string
          quoted_span_end: number | null
          quoted_span_start: number | null
          quoted_text: string | null
          scoring_version: number
          segment_id: string
          stance: string
        }
        Insert: {
          confidence: number
          created_at?: string
          extraction_id?: string
          model_id: string
          model_version?: string
          proposition_id: string
          quoted_span_end?: number | null
          quoted_span_start?: number | null
          quoted_text?: string | null
          scoring_version?: number
          segment_id: string
          stance: string
        }
        Update: {
          confidence?: number
          created_at?: string
          extraction_id?: string
          model_id?: string
          model_version?: string
          proposition_id?: string
          quoted_span_end?: number | null
          quoted_span_start?: number | null
          quoted_text?: string | null
          scoring_version?: number
          segment_id?: string
          stance?: string
        }
        Relationships: [
          {
            foreignKeyName: "stance_extractions_proposition_id_fkey"
            columns: ["proposition_id"]
            isOneToOne: false
            referencedRelation: "proposition_bank"
            referencedColumns: ["proposition_id"]
          },
          {
            foreignKeyName: "stance_extractions_segment_id_fkey"
            columns: ["segment_id"]
            isOneToOne: false
            referencedRelation: "segments"
            referencedColumns: ["id"]
          },
        ]
      }
      stories: {
        Row: {
          algo_version: number
          claim_centroid: string | null
          created_at: string
          entities: string[]
          event_count: number
          id: string
          summary: string | null
          title: string | null
          topics: string[]
          updated_at: string
        }
        Insert: {
          algo_version?: number
          claim_centroid?: string | null
          created_at?: string
          entities?: string[]
          event_count?: number
          id?: string
          summary?: string | null
          title?: string | null
          topics?: string[]
          updated_at?: string
        }
        Update: {
          algo_version?: number
          claim_centroid?: string | null
          created_at?: string
          entities?: string[]
          event_count?: number
          id?: string
          summary?: string | null
          title?: string | null
          topics?: string[]
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      pipeline_stage_metrics_hourly: {
        Row: {
          fail_rate: number | null
          failed_count: number | null
          hour_bucket: string | null
          ok_count: number | null
          p50_ms: number | null
          p95_ms: number | null
          stage: string | null
          total: number | null
        }
        Relationships: []
      }
    }
    Functions: {
      backfill_rescore_batch: {
        Args: { batch_size?: number; reset_synthesis?: boolean }
        Returns: {
          claim_rows_reset: number
          doc_id: string
          document_updated: boolean
          synthesis_reset: boolean
        }[]
      }
      enqueue_stage_if_new: {
        Args: {
          p_attempt?: number
          p_doc_id: string
          p_stage: string
          p_status_token: string
        }
        Returns: boolean
      }
      enqueue_stuck_docs: {
        Args: { target_stage: string; target_status: string }
        Returns: number
      }
      get_null_embedding_propositions: {
        Args: { row_limit?: number }
        Returns: {
          id: string
          prop_text: string
        }[]
      }
      get_null_embedding_segments: {
        Args: { row_limit?: number }
        Returns: {
          id: string
          text_content: string
        }[]
      }
      match_event_centroids: {
        Args: {
          match_count?: number
          match_threshold?: number
          query_embedding: string
          time_end?: string
          time_start?: string
        }
        Returns: {
          entities: string[]
          event_id: string
          event_key: string
          event_type: string
          geo_primary: string
          similarity: number
        }[]
      }
      match_segments: {
        Args: {
          exclude_document_id?: string
          match_count?: number
          match_threshold?: number
          query_embedding: string
        }
        Returns: {
          document_id: string
          id: string
          label: string
          position_index: number
          similarity: number
          text_content: string
        }[]
      }
      pgmq_archive: {
        Args: { msg_id: number; queue_name: string }
        Returns: boolean
      }
      pgmq_read: {
        Args: { qty: number; queue_name: string; vt: number }
        Returns: {
          enqueued_at: string
          message: Json
          msg_id: number
          read_ct: number
          visible_at: string
        }[]
      }
      pgmq_send: { Args: { msg: Json; queue_name: string }; Returns: number }
      pipeline_ops_summary: { Args: never; Returns: Json }
      pipeline_reap_poisoned: {
        Args: { p_batch_size?: number; p_max_read_ct?: number }
        Returns: number
      }
      pipeline_record_stage_metric: {
        Args: {
          p_attempt: number
          p_document_id: string
          p_duration_ms: number
          p_error_message: string
          p_stage: string
          p_status: string
        }
        Returns: undefined
      }
      pipeline_stage_is_paused: { Args: { p_stage: string }; Returns: boolean }
      pipeline_stage_mark_failure: {
        Args: {
          p_cooldown_minutes?: number
          p_reason: string
          p_stage: string
          p_threshold?: number
        }
        Returns: undefined
      }
      pipeline_stage_mark_success: {
        Args: { p_stage: string }
        Returns: undefined
      }
      pipeline_status_to_stage: { Args: { status: string }; Returns: string }
      preview_rescore_batch: {
        Args: { batch_size?: number }
        Returns: {
          created_at: string
          has_scores: boolean
          has_strip: boolean
          id: string
          pipeline_status: string
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
